/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LunarYogaRouteImport } from './routes/lunar-yoga'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as UploadDocumentsRouteImport } from './routes/upload-documents'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminAboutCropRouteImport } from './routes/admin.about.crop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LunarYogaRoute = LunarYogaRouteImport.update({
  id: '/lunar-yoga',
  path: '/lunar-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadDocumentsRoute = UploadDocumentsRouteImport.update({
  id: '/upload-documents',
  path: '/upload-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutCropRoute = AdminAboutCropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => AdminAboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/lunar-yoga': typeof LunarYogaRoute
  '/offerings': typeof OfferingsRoute
  '/upload-documents': typeof UploadDocumentsRoute
  '/videos': typeof VideosRoute
  '/admin/about': typeof AdminAboutRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/about/crop': typeof AdminAboutCropRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/lunar-yoga': typeof LunarYogaRoute
  '/offerings': typeof OfferingsRoute
  '/upload-documents': typeof UploadDocumentsRoute
  '/videos': typeof VideosRoute
  '/admin/about': typeof AdminAboutRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/about/crop': typeof AdminAboutCropRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/lunar-yoga': typeof LunarYogaRoute
  '/offerings': typeof OfferingsRoute
  '/upload-documents': typeof UploadDocumentsRoute
  '/videos': typeof VideosRoute
  '/admin/about': typeof AdminAboutRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/about/crop': typeof AdminAboutCropRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/astrology'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/lunar-yoga'
    | '/offerings'
    | '/upload-documents'
    | '/videos'
    | '/admin/about'
    | '/admin/applications'
    | '/admin/blog'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/pricing'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/about/crop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/astrology'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/lunar-yoga'
    | '/offerings'
    | '/upload-documents'
    | '/videos'
    | '/admin/about'
    | '/admin/applications'
    | '/admin/blog'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/pricing'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/about/crop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/astrology'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/lunar-yoga'
    | '/offerings'
    | '/upload-documents'
    | '/videos'
    | '/admin/about'
    | '/admin/applications'
    | '/admin/blog'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/pricing'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/about/crop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AstrologyRoute: typeof AstrologyRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  LunarYogaRoute: typeof LunarYogaRoute
  OfferingsRoute: typeof OfferingsRoute
  UploadDocumentsRoute: typeof UploadDocumentsRoute
  VideosRoute: typeof VideosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lunar-yoga': {
      id: '/lunar-yoga'
      path: '/lunar-yoga'
      fullPath: '/lunar-yoga'
      preLoaderRoute: typeof LunarYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-documents': {
      id: '/upload-documents'
      path: '/upload-documents'
      fullPath: '/upload-documents'
      preLoaderRoute: typeof UploadDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about/crop': {
      id: '/admin/about/crop'
      path: '/crop'
      fullPath: '/admin/about/crop'
      preLoaderRoute: typeof AdminAboutCropRouteImport
      parentRoute: typeof AdminAboutRoute
    }
  }
}

interface AdminAboutRouteChildren {
  AdminAboutCropRoute: typeof AdminAboutCropRoute
}

const AdminAboutRouteChildren: AdminAboutRouteChildren = {
  AdminAboutCropRoute: AdminAboutCropRoute,
}

const AdminAboutRouteWithChildren = AdminAboutRoute._addFileChildren(
  AdminAboutRouteChildren,
)

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRouteWithChildren
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRouteWithChildren,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AstrologyRoute: AstrologyRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  LunarYogaRoute: LunarYogaRoute,
  OfferingsRoute: OfferingsRoute,
  UploadDocumentsRoute: UploadDocumentsRoute,
  VideosRoute: VideosRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
